-- Eliminar duplicados de la tabla existente
DELETE FROM TRANSACTIONS
WHERE (CLIENT_ID, CLIENT_NAME, CLIENT_LASTNAME, EMAIL, STORE_ID, STORE_NAME, LOCATION, PRODUCT_ID, PRODUCT_NAME, CATEGORY, BRAND, ADDRESS_ID, STREET, CITY, STATE, ZIP_CODE, TRANSACTION_ID, QUANTITY_OF_ITEMS_SOLD, UNIT_PRICE, DISCOUNT) 
IN (
    SELECT CLIENT_ID, CLIENT_NAME, CLIENT_LASTNAME, EMAIL, STORE_ID, STORE_NAME, LOCATION, PRODUCT_ID, PRODUCT_NAME, CATEGORY, BRAND, ADDRESS_ID, STREET, CITY, STATE, ZIP_CODE, TRANSACTION_ID, QUANTITY_OF_ITEMS_SOLD, UNIT_PRICE, DISCOUNT
    FROM (
        SELECT CLIENT_ID, CLIENT_NAME, CLIENT_LASTNAME, EMAIL, STORE_ID, STORE_NAME, LOCATION, PRODUCT_ID, PRODUCT_NAME, CATEGORY, BRAND, ADDRESS_ID, STREET, CITY, STATE, ZIP_CODE, TRANSACTION_ID, QUANTITY_OF_ITEMS_SOLD, UNIT_PRICE, DISCOUNT,
               ROW_NUMBER() OVER (PARTITION BY CLIENT_ID, CLIENT_NAME, CLIENT_LASTNAME, EMAIL, STORE_ID, STORE_NAME, LOCATION, PRODUCT_ID, PRODUCT_NAME, CATEGORY, BRAND, ADDRESS_ID, STREET, CITY, STATE, ZIP_CODE, TRANSACTION_ID, QUANTITY_OF_ITEMS_SOLD, UNIT_PRICE, DISCOUNT ORDER BY CLIENT_ID) AS rn
        FROM TRANSACTIONS
    ) AS tmp
    WHERE rn > 1
);

-- Rellenar valores nulos en columnas numéricas con 0
UPDATE TRANSACTIONS
SET
CLIENT_ID = COALESCE(CLIENT_ID, 0),
STORE_ID = COALESCE(STORE_ID, 0),
ADDRESS_ID = COALESCE(ADDRESS_ID, 0),
ZIP_CODE = COALESCE(ZIP_CODE, 0),
TRANSACTION_ID = COALESCE(TRANSACTION_ID, 0),
QUANTITY_OF_ITEMS_SOLD = COALESCE(QUANTITY_OF_ITEMS_SOLD, 0),
UNIT_PRICE = COALESCE(UNIT_PRICE, 0),
DISCOUNT = COALESCE(DISCOUNT, 0);

-- Rellenar valores nulos en la tabla TRANSACTIONS
UPDATE TRANSACTIONS
SET
CLIENT_NAME = COALESCE(CLIENT_NAME, 'Not Found'),
CLIENT_LASTNAME = COALESCE(CLIENT_LASTNAME, 'Not Found'),
EMAIL = COALESCE(EMAIL, 'Not Found'),
STORE_NAME = COALESCE(STORE_NAME, 'Not Found'),
LOCATION = COALESCE(LOCATION, 'Not Found'),
PRODUCT_NAME = COALESCE(PRODUCT_NAME, 'Not Found'),
CATEGORY = COALESCE(CATEGORY, 'Not Found'),
BRAND = COALESCE(BRAND, 'Not Found'),
STREET = COALESCE(STREET, 'Not Found'),
CITY = COALESCE(CITY, 'Not Found'),
STATE = COALESCE(STATE, 'Not Found')


